### ISSUE TITLE
Inconsistency between the training data and the eval’s image rendering in MetaWorld.

### ISSUE THREAD

**Issue by AdaChambers** [siddhanthaldar/BAKU#10] opened 2024-09-01 07:42 UTC
When I run
`python eval.py agent=baku suite=metaworld dataloader=metaworld suite/task=metaworld suite.hidden_dim=256 bc_weight=weights/metaworld/baku.pt use_proprio=false`
I find that the image of the eval rollout is like:
![image](https://github.com/user-attachments/assets/cbe1d1ee-78a0-4e44-ac97-6b3d7eba7ce5)

However the image in the metaworld expert_demo dataset is like:
![image](https://github.com/user-attachments/assets/fa93dc4e-1262-426d-a2a4-24d5cb8cf220)

The inconsistency may cause bad performance (almost 0% success rate) of the pretrained model. So a natural question is whether the Metaworld‘s env_wrapper rendering code is missing some  image cropping operations or something else? 
Looking forward to anyone's response!

**Comment by ATriplez** [comment] 2024-09-11 07:36
Hi, I had the same problem at first. At last I found out that the cause was my own installation of metaworld rather than using the version provided by the author which is below. I hope it will be helpful.

https://github.com/siddhanthaldar/Metaworld/tree/65a7c33c8326cadfef7e19590af98b2bf2640cb7

**Comment by siddhanthaldar** [comment] 2024-09-17 03:07
I am closing this issue since it seems solved.

**Closed as completed by siddhanthaldar** 2024-09-17 03:07 UTC

**Comment by Holmes-GU** [comment] 2024-11-21 05:58
> Hi, I had the same problem at first. At last I found out that the cause was my own installation of metaworld rather than using the version provided by the author which is below. I hope it will be helpful.
> 
> https://github.com/siddhanthaldar/Metaworld/tree/65a7c33c8326cadfef7e19590af98b2bf2640cb7

Hi,

If I use the installation instruction provided by the about link, the problem can be successfully solved?

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/abf9afcc-7ac6-4644-a1f6-7ffc75d1673f">

**Comment by ATriplez** [comment] 2024-11-25 09:08
I think you shold:
git clone https://github.com/siddhanthaldar/Metaworld.git
That should solve the problem.

> > Hi, I had the same problem at first. At last I found out that the cause was my own installation of metaworld rather than using the version provided by the author which is below. I hope it will be helpful.
> > https://github.com/siddhanthaldar/Metaworld/tree/65a7c33c8326cadfef7e19590af98b2bf2640cb7
> 
> Hi,
> 
> If I use the installation instruction provided by the about link, the problem can be successfully solved?
> 
> <img alt="image" width="1025" src="https://private-user-images.githubusercontent.com/55798572/388374019-abf9afcc-7ac6-4644-a1f6-7ffc75d1673f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjU3NDUsIm5iZiI6MTczMjUyNTQ0NSwicGF0aCI6Ii81NTc5ODU3Mi8zODgzNzQwMTktYWJmOWFmY2MtN2FjNi00NjQ0LWExZjYtN2ZmYzc1ZDE2NzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNjk1MjFkMTkwZDA3MDFkZmM1MDA5MWZjZjhkNDAzMzdkY2JiZTJkNjVjNGM4OWE1MTQwNGQwYjQ5ZGI0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EG2lTYCvtsd1igNr91UZgAlIzAlZda8ejD8bPm6AikQ">
